### ISSUE TITLE
Read SAM file?

### ISSUE THREAD

**Issue by dcroote** [rust-bio/rust-htslib#119]
Hi, I am looking to use the SAM output of bowtie2 in Rust and looking through the `sam` module I see a `Writer` struct, but no corresponding `Reader` struct as is present in the `bam` module. Poking around a bit more, it appears like much of code for reading in a SAM file would be similar to BAM, with some minor modifications, such as `htslib::htsFile` instead of `htslib::BGZF`, `htslib::sam_read1` instead of `htslib::bam_read1` etc... If there is no current way to read SAM files I could give it a shot, but I am pretty new to Rust and would need some guidance on code reuse between sam/bam and namespace issues i.e. `prelude.rs` has `pub use bam::Read;`

Thanks!
Derek

**Comment by dlaehnemann** [comment]
Hi Derek,

I think a quick workaround -- which you probably found already -- is to transform the bowtie2 output to bcf, e.g. with [samtools view](http://www.htslib.org/doc/samtools.html). That is probably also the reason, why there is no SAM `Reader` yet, because people will often directly pipe their output into samtools to get out a smaller BAM file.

But from a quick glance at the `sam` and `bam` module, it does look like most of it could be implemented in equivalance to `bam`. The relevant `htslib` functions to wrap are listed (and some documented) over <https://github.com/samtools/htslib/blob/develop/htslib/sam.h>, in the `SAM I/O` and `BAM I/O` sections, and actual implementations in the [corresponding `sam.c` file](https://github.com/samtools/htslib/blob/develop/sam.c). I have previously also contributed mostly by working off of similar code that was present, so that should be a good place to start. And I am sure @johanneskoester (and others, like me) will chip in with useful feedback for any code suggestions... ;)

As for `prelude.rs`, this looks pretty dead and unused, so maybe something to get rid of, @johanneskoester?

**Comment by johanneskoester** [comment]
Indeed. We would be very thankful for any contribution in this direction. So far, SAM simply was not high priority.

**Comment by johanneskoester** [comment]
Reader and writer should now support all formats.
