### ISSUE TITLE
tbx::Reader can no longer read indexed text files with version 0.27+: "Error: invalid tabix index"

### ISSUE THREAD

**Issue by felix-clark** [rust-bio/rust-htslib#194]
I am trying to use the `tbx::Reader` read an indexed ~~BED~~ text file with data lines of the form
```
<chrom>    <pos>    <data...>
```
that have `.tbi` index files generated with `tabix -b2 -e2 <file>.bed.gz`. Calling `tbx::Reader::from_path()` works as expected in verion 0.26, but generates an error "invalid tabix index" in 0.27 and later. ~~Version 0.27 of `rust-htslib` changes the type of the index from 32 bits to 64 bits, presumably to keep up with the changes in HTSlib. (this is unrelated)~~ I have tried using a recent version of tabix (1.10.2) and re-indexing the file, but this did not solve the issue (and in fact the resulting `.tbi` index file appears to be identical).

I apologize for not having the time to dive into this further myself right now, and it's possible that the underlying HTSlib C library is ultimately at fault, but I thought I'd create the issue now in case someone else is experiencing it.

**Comment by juliangehring** [comment]
@felix-clark I tried reproducing this with a simple data set

```
chr7    127471196       1
chr7    127472363       2
chr7    127473530       3
chr7    127474697       4
chr7    127475864       5
```

and tabix 1.10.2, but didn't see any errors with v0.26.0 to v0.30.0.

Is there a data set which gives you the error and that you can share for reproducing this issue?

**Comment by felix-clark** [comment]
@juliangehring It seems like commented header lines are responsible. Perhaps you could  prepend that data with a line like `#contig pos     data`?

**Comment by juliangehring** [comment]
Okay, the header line makes all the difference - I can reproduce it when the file has a header line.

It seems that this is caused by the file format recognition in htslib. Without the header, it recognises the file format category as a region list. With the header, it classifies it as a general text file and puts in the unknown file format category - this is why the the safety checks in `Reader::new` fail and the `InvalidIndex` is raised.

Maybe the safety checks for the correct file formats can be extended a bit to support more formats, including files that are not properly recognised. However, it ultimately looks like a bug in htslib to me.

**Comment by felix-clark** [comment]
This doesn't appear to have been flagged as an issue in htslib in the time since the last discussion here, but it does seem like something that should ideally be addressed upstream.

I submitted a proposed PR here to permit this particular case along with some tests and test files, both positive and negative. It should definitely be reviewed by an expert.

**Comment by felix-clark** [comment]
I dug into htslib and I think I understand a little better what happened. The changelog here:
https://github.com/samtools/htslib/blob/82d01ba63b20eed8905ea60c2e1cfe0f96c73bab/NEWS#L222
indicates that previously `hts_detect_format()` would report all text files as being of SAM format, which explains why the check here permitted files with an exact format type of `sam`. These will now be reported as a generic `text_format` (unless, presumably, the file is indeed a sam file).

I believe this means that simply changing the exact format enum from "sam" to "text_format" will effectively yield the old behaviour for these sort of custom BED files.

The one question I have is whether there is a use case for the `tbx::Reader` with SAM files. I would think that these would typically be covered by the bam reader but I don't want to make assumptions about what people might be doing. If that is a sensible use case then we would want to allow "sam" format in addition to "text_format", which is probably the closest to the old behaviour.

**Comment by brainstorm** [comment]
Hello @felix-clark 

I believe @jmarshall has recently been working on addressing BED file standardization over hts-specs (or at least, I've seen recent discussions on this topic). I would indeed report your findings upstream, this information/feedback can be very useful for the @samtools htslib team.

**Comment by jmarshall** [comment]
@brainstorm's belief is incorrect: it is a different group of people who are working on formalising BED at present. However BED standardisation is irrelevant here, except insofar as an eventual `##BED` or similar header would allow HTSlib's format detection to return BED in more cases rather than a more generic `text_format`.

Command-line `tabix` works fine on your example, either with or without a header line, in both 1.10.2 and current **develop**. BTW the OP's `<chrom>    <pos>    <data...>` description and the example in https://github.com/rust-bio/rust-htslib/issues/194#issuecomment-621980109 are not BED files or any kind of HTSlib `region_list` file, but nonetheless with `-b2 -e2` they can be processed by tabix.

The problem is that tabix and tabix indexes work with arbitrary position-sorted data, not just BED files and not just files in HTSLib's `region_list` category. So the problem is in rust-htslib; this test is just not appropriate:

https://github.com/rust-bio/rust-htslib/blob/e979e3446ecc5d18b2dc518c0dcffb1cbdde324d/src/tbx/mod.rs#L155-L156

Also FFS use `hts_get_format()` instead of peering directly into the `htsFile`'s private innards.

**Comment by dlaehnemann** [comment]
Thanks for chiming in here and providing several very useful pointers, @jmarshall !

At the same time: Your language comes across as both aggressive and demotivating to me. I am assuming that FFS stands for `for fucks sake` and am reading statements like `@brainstorm's belief is incorrect` and `this test is just not appropriate` as blunt expressions of a bad mood rather than a justified level of annoyance at someone who might have repeatedly not listened to advice, but please correct me if I'm wrong. This may seem like an overreaction on my part, but I do believe that respectful, appreciative and empathetic communication are essential to make and keep any project as welcoming as possible, which I think is especially important for open source projects sustained only by volunteers. And in communication very subtle things can make a big difference.

But as I said at the start, all of the criticism you voice is very welcome contentwise. Thanks for taking so much time in tracking this issue down and providing this write-up. We'll have to revisit the checks made for tbx-indexed files.

**Comment by jmarshall** [comment]
Some aspects of what you say are wrong, but that is by the by. I checked for the presence of a CoC or other signals before using blunt language like ‘FFS’, but it is reasonable to find that usage unnecessary and I apologise.

As I too am a volunteer who was specifically invoked and asked by @brainstorm to look into your problems here, I do not apologise for “[this] belief is incorrect” or “this test … not appropriate”, which I see as simply factual statements.

**Comment by dlaehnemann** [comment]
Thanks for the apology for `FFS` and your open and clear response.

Regarding the other two phrases I mentioned, I was trying to point out how it comes across to me and how I think this affects communication in a community. So I was definitely not asking for an apology, simply trying to provide feedback. And do feel free to specifically criticize anything I say.

Also, thanks for pointing out the lack of a CoC. I had been thinking we should probably set one up for the `rust-bio` projects and if it does provide guidance to contributors beyond the symbolic gesture, I think this becomes even more important.

**Comment by felix-clark** [comment]
Thanks for the useful feedback, @jmarshall . I've minimally updated PR #226 to reflect your clarification and suggestion to use `hts_get_format()`.

So I guess the (open?) question is whether to skip these checks on the file format entirely. I can confirm that removing them does not induce any unit test breakage. Can anyone else comment on why these checks were present in the first place, or propose any other problems that might arise by just removing them? Naively it seems reasonable that they are superfluous; given that a file has been successfully indexed by `tabix` in some way, I would think that the `tbx::Reader` should be able to handle it.

**Comment by felix-clark** [comment]
Since no one has jumped in with any reason why explicit format checks are necessary in `tbx::Reader::new()`, I've removed the check in PR #226 . It's now ready for review.
