### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by lskatz** [rust-bio/rust-htslib#198]
Need to add more documentation and examples.  I tried to see how to extract bam header information and it is basically nondescriptive.

**Comment by lskatz** [comment]
Please add that the build requires `PKG_CONFIG_PATH=/lib64/pkgconfig` at least on CentOS

**Comment by lskatz** [comment]
There is an unlisted LLVM requirement

**Comment by dlaehnemann** [comment]
To frame this issue a slight bit more motivatingly, I changed its title. Also, over at `rust-bio`, we're starting a docathon next week. We'll see what we learn from that experience and then maybe repeat it over here at some point. Feel free to join in:
https://github.com/rust-bio/rust-bio/issues/276

**Comment by brainstorm** [comment]
Simple examples like https://github.com/rust-bio/rust-htslib/issues/228 are worth adding in the documentation, indeed.

**Comment by brainstorm** [comment]
> Please add that the build requires `PKG_CONFIG_PATH=/lib64/pkgconfig` at least on CentOS

Can't reproduce :-S... OTOH that shouldn't be needed nowadays with the docker container building process.

**Comment by brainstorm** [comment]
Thanks for the criticism @lskatz, we'll try to tackle your feedback soon. Needless to say, you are very much welcome to join the effort:

https://github.com/rust-bio/rust-htslib/issues/244

I've separated the issues so that they are a bit more specific and easy to tackle in bite sizes:

https://github.com/rust-bio/rust-htslib/issues/245
https://github.com/rust-bio/rust-htslib/issues/246

But please feel free to add snippets you'd like to see as separate, specific issues? Thanks in advance!
