### ISSUE TITLE
Static compilation possible?

### ISSUE THREAD

**Issue by wwood** [rust-bio/rust-htslib#80]
Hi,

I'm trying to create a static binary for a project of mine https://github.com/wwood/CoverM but i'm running into an issue: 
```
$ rustup target add x86_64-unknown-linux-musl
...
$ cargo build --target x86_64-unknown-linux-musl --release
...
/usr/bin/ld: /home/ben/git/coverm/target/x86_64-unknown-linux-musl/release/deps/librust_htslib-f71d6303e993dcd2.rlib(sam_header.o): undefined reference to symbol '__printf_chk@@GLIBC_2.3.4'
```
Is it possible to get a static compile of a project using rust-htslib? Am I doing something incorrectly?
ta, ben

**Comment by johanneskoester** [comment]
Static building is fine. I do that all the time. However, HTSlib needs glibc >= 2.3.4. You are trying to build on musl instead. I don't know if that is supported. I suggest asking the htslib guys.

**Comment by johanneskoester** [comment]
Closing for now, feel free to reopen if you disagree or new issues arise.

**Comment by wwood** [comment]
Thanks, I would be happy to use glibc. However, after a frustrating amount of internet searching I'm finding it difficult to work out how, exactly. Would you mind sharing your secret? I'm looking to build an executable.

Apologies if this is a naive question, I just figure you might have a solution easily at hand.
Thanks, ben

**Comment by johanneskoester** [comment]
glibc should be the default on most linux distributions. So, if you e.g. run on Ubuntu or Fedora, it will use a new enough glibc automatically. Unfortunately, if your system uses musl, you might need to do the build inside a container or a virtual machine, or try to figure out how to switch to glibc on your system.

**Comment by wwood** [comment]
Right, glibc is the default on my (Ubuntu/GNU Guix) system. I installed the musl toolchain with rustup specifically for the purpose of static compilation, following this advice:

> Static linking is supported via an alternative libc, musl.

https://doc.rust-lang.org/1.12.1/book/advanced-linking.html#static-linking

Compiling with the musl toolchain gives a static binary by default, where the glibc toolchain does not (I tried using `ldd` and it failed to run on another system). Do you have any suggestions on how to ask for a static compilation with the glibc toolchain, or some other solution?

Thanks, ben

**Comment by johanneskoester** [comment]
Ok, so you want the libc to be statically linked as well. This is indeed not possible if you depend on htslib, since that requires glibc as far as I know. However, please note that statically  linking glibc into a binary is usually not necessary. It is present on virtually every system. All you need is to build your binary on an old enough linux, because glibc is forward compatible. By e.g. building on centos 6, it should work on all newer linuxes. The problem you have is that your ubuntu has a too new glibc for many other linuxes I guess.

Instead of trying to build a compatible binary on your own (I guess  for distribution), please consider providing your package via [Bioconda](https://bioconda.github.io), which solves such problems for you.

**Comment by wwood** [comment]
OK, thanks for the suggestions. I'll figure something out.
